IndexError: list index out of range
When running proton manually I get `IndexError: list index out of range` from https://github.com/simons-public/protonfixes/blob/master/protonfixes/fix.py#L35 so let's catch that error too.
This probably happens because the `$PWD` is in an unexpected directory.